# This is a Terraform-managed file; manual changes will be overwritten.
# see https://github.com/workloads/github-organization/blob/main/templates/workflows/terraform.yml

---
name: "Code Quality: Terraform"

# yamllint disable-line rule:truthy
on:
  push:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      # see https://github.com/actions/checkout
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # see https://github.com/hashicorp/setup-terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          terraform_version: ${{ secrets.TERRAFORM_VERSION }}

      - name: Initialize Terraform for Module
        run: terraform init
        env:
          working-dir: "./"

      - name: Format Terraform code for Module
        run: terraform fmt -check -recursive
        env:
          working-dir: "./"
