# This is a Terraform-managed file; manual changes will be overwritten.
# see https://github.com/workloads/github-organization/blob/main/templates/workflows/terraform-docs.tftpl.yml

---

name: "Documentation: terraform-docs"

# yamllint disable-line rule:truthy
on:
  push:

# see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions: read-all

jobs:
  workflow:
    # only run if workflows are enabled
    if: ${{ vars.ENABLE_WORKFLOWS == 'true' }}

    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
    concurrency:
      group: "${{ github.workflow }}-${{ github.ref }}"
      cancel-in-progress: true

    name: Terraform Docs

    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # see https://github.com/actions/checkout/releases/tag/v3.5.3
      - name: Checkout Repository
        uses: "actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9" # ref: `tags/v3.5.3`
        with:
          ref: "${{ github.event.pull_request.head.ref }}"
          fetch-depth: 1

      # see https://github.com/terraform-docs/gh-actions/releases/tag/v1.0.0
      - name: Render documentation for repository and push changes back to branch
        uses: "terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0" # ref: `tags/v1.0.0`
        with:
          config-file: ".terraform-docs.yml"
          output-file: "README.md"
          output-method: inject"
          git-push: true
          working-dir: "./"

  workflow-inactive:
    # only run if workflows are disabled
    if: ${{ vars.ENABLE_WORKFLOWS != 'true' }}

    name: Workflow Status
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Display Workflow Status
        run: echo "::warning ::Workflow is not currently active. Check if `ENABLE_WORKFLOWS` is set to `true`."
